import pandas as pd
import numpy as np
from pathlib import Path

class SignalBacktester:
    """Backtester that trades based on discrete signals from analysis CSV.

    It joins price data with an "analysis" file generated by dataAnalysis.py
    and evaluates simple long-only strategies triggered by indicator values.

    Usage example:

        backtester = SignalBacktester(
            price_csv='Data/backtestingData.csv',
            analysis_csv='Data/dataAnalysis.csv',
            start_date='2000-01-01', end_date='2026-01-01'
        )
        metrics = backtester.run()

    By default every indicator has a built-in bullish condition:
        * SMA_Trend == 'Strong Uptrend'
        * EMA_Trend == 'Strong Uptrend'
        * MACD_Trend == 'Bullish Momentum'
        * ADX_Trend contains 'Strong'
        * RSI_Trend == 'Oversold'
        * OBV_Trend == 'Buying Pressure'

    The run() method returns a DataFrame with per-signal performance metrics
    and writes both CSV and XLSX versions of the results.
    """

    DEFAULT_BULLISH = {
        'SMA_Trend': ['Strong Uptrend'],
        'EMA_Trend': ['Strong Uptrend'],
        'MACD_Trend': ['Bullish Momentum'],
        'ADX_Trend': ['Strong Trend', 'Very Strong Trend', 'Extremely Strong Trend'],
        'RSI_Trend': ['Oversold'],
        'OBV_Trend': ['Buying Pressure'],
    }

    def __init__(self, price_csv, analysis_csv, start_date=None, end_date=None):
        self.price_csv = Path(price_csv)
        self.analysis_csv = Path(analysis_csv)
        self.start_date = pd.to_datetime(start_date) if start_date is not None else None
        self.end_date = pd.to_datetime(end_date) if end_date is not None else None
        self._load()

    def _load(self):
        # price data must contain Date,Ticker,Close (and optionally Open)
        self.prices = pd.read_csv(self.price_csv, parse_dates=['Date'], dayfirst=False)
        self.analysis = pd.read_csv(self.analysis_csv, parse_dates=['Date'], dayfirst=False)

        # apply date filters if provided
        if self.start_date is not None:
            self.prices = self.prices[self.prices['Date'] >= self.start_date]
            self.analysis = self.analysis[self.analysis['Date'] >= self.start_date]
        if self.end_date is not None:
            self.prices = self.prices[self.prices['Date'] <= self.end_date]
            self.analysis = self.analysis[self.analysis['Date'] <= self.end_date]

        # merge for convenience; some dates may not align
        self.data = pd.merge(self.analysis, self.prices,
                             on=['Ticker', 'Date'], how='left',
                             suffixes=('_sig', '_price'))
        # forward-fill missing price forward one row could be considered but leave NaNs

    def run(self, signals=None, lookahead=1):
        """Compute returns for each requested signal.

        Parameters
        ----------
        signals : dict, optional
            mapping column name -> list of values considered bullish.  If None,
            DEFAULT_BULLISH is used.
        lookahead : int
            number of trading days to hold after signal (default 1).

        Returns
        -------
        metrics_df : pd.DataFrame
            DataFrame containing per-signal Sharpe, max drawdown, average return,
            and number of trades.
        """
        if signals is None:
            signals = self.DEFAULT_BULLISH

        results = []

        # ensure prices sorted per ticker/date
        self.data = self.data.sort_values(['Ticker', 'Date']).reset_index(drop=True)
        # compute forward returns based on close price
        self.data['Return'] = self.data.groupby('Ticker')['Close'].pct_change(periods=lookahead).shift(-lookahead)

        for col, goodvals in signals.items():
            mask = self.data[col].isin(goodvals)
            trades = self.data.loc[mask, ['Ticker', 'Date', 'Close', 'Return']].dropna()
            returns = trades['Return'].values
            sharpe, maxdd = self._compute_metrics(returns)
            avg_ret = np.nanmean(returns) if returns.size > 0 else np.nan
            results.append({
                'Signal': col,
                'n_trades': len(returns),
                'avg_return': avg_ret,
                'Sharpe': sharpe,
                'MaxDrawdown': maxdd,
            })

        metrics_df = pd.DataFrame(results).set_index('Signal')
        # save outputs
        out_csv = self.analysis_csv.with_name('signal_backtest_metrics.csv')
        metrics_df.to_csv(out_csv)
        out_xlsx = out_csv.with_suffix('.xlsx')
        metrics_df.to_excel(out_xlsx)
        return metrics_df

    def _compute_metrics(self, returns):
        if len(returns) == 0:
            return np.nan, np.nan
        r = pd.Series(returns).dropna()
        if r.empty or r.std() == 0:
            return np.nan, np.nan
        sharpe = r.mean() / r.std() * np.sqrt(252)
        cum = (1 + r).cumprod()
        dd = cum / cum.cummax() - 1
        return sharpe, dd.min()


if __name__ == '__main__':
    sb = SignalBacktester(
        price_csv='D:/Code/Python/New folder (2)/researchProject/Data/backtestingData.csv',
        analysis_csv='D:/Code/Python/New folder (2)/researchProject/Data/dataAnalysis.csv',
        start_date='2000-01-01', end_date='2026-01-01'
    )
    metrics = sb.run()
    print('Signal backtest metrics:')
    print(metrics)
